{
 "title": "Primary Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Device Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "table": "measurements",
     "where": [
      {
       "type": "macro",
       "name": "$__timeFilter",
       "params": []
      }
     ],
     "select": [
      [
       { "type": "column", "params": [ "battery_level" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Data Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "table": "measurements",
     "where": [
      {
       "type": "macro",
       "name": "$__timeFilter",
       "params": []
      }
     ],
     "select": [
      [
       { "type": "column", "params": [ "station_id" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reflector Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "select": [
      [
       { "params": [ "reflector_height" ], "type": "column" }
      ]
     ],
     "table": "measurements",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Reflector Height Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "reflector_height" ], "type": "column" }
      ]
     ],
     "table": "measurements",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Station Locations",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "station_name" ], "type": "column" },
       { "params": [ "latitude" ], "type": "column" },
       { "params": [ "longitude" ], "type": "column" },
       { "params": [ "reflector_height" ], "type": "column" }
      ]
     ],
     "table": "stations",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  }
 ]
}