apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: user
    password: password
    jsonData:
      database: riversense
      sslmode: 'disable'
      timescaledb: true